# Generated by Django 4.1.5 on 2023-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_habit_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
