# Generated by Django 4.2a1 on 2023-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habittracker", "0003_remove_user_bio_remove_user_birth_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(
                fields=("habit", "date"), name="unique_record"
            ),
        ),
    ]
