# Generated by Django 4.2a1 on 2023-01-27 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habittracker", "0004_record_unique_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-date"]},
        ),
    ]
